In [122]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_excel('C:/Users/Alejandro/OneDrive/Documents/GitHub/Bootcamp2026-1/Documentos/MES_1225.xlsx')

In [79]:
df.head(20)

,The Monthly electricity data explorer and the main highlights are available here: https://www.iea.org/reports/monthly-electricity-statistics-overview,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5
0,NaN,NaN,NaN,NaN,NaN,NaN
1,False,NaN,NaN,NaN,NaN,NaN
2,"In particular, external dissemination of any I...",NaN,NaN,NaN,NaN,NaN
3,Please contact us at stats@iea.org if you have...,NaN,NaN,NaN,NaN,NaN
4,Last update:,15 March 2026,NaN,NaN,NaN,NaN
5,"This notice, and any copyright or sourcing sta...",NaN,NaN,NaN,NaN,NaN
6,NaN,NaN,NaN,NaN,NaN,NaN
7,Country,Time,Balance,Product,Value,Unit
8,Australia,December 2025,Net Electricity Production,Electricity,23360.4375,GWh
9,Australia,December 2025,Net Electricity Production,Hydro,932.8479,GWh
10,Australia,December 2025,Net Electricity Production,Total Combustible Fuels,12210.7489,GWh
11,Australia,December 2025,Net Electricity Production,"Coal, Peat and Manufactured Gases",8782.6749,GWh
12,Australia,December 2025,Net Electricity Production,Oil and Petroleum Products,293.4672,GWh
13,Australia,December 2025,Net Electricity Production,Natural Gas,2948.0199,GWh
14,Australia,December 2025,Net Electricity Production,Combustible Renewables,186.5869,GWh
15,Australia,December 2025,Net Electricity Production,Solar,6688.7891,GWh
16,Australia,December 2025,Net Electricity Production,"Total Renewables (Hydro, Geo, Solar, Wind, Other)",11336.2756,GWh
17,Australia,December 2025,Used for pumped storage,Electricity,80.4632,GWh
18,Australia,December 2025,Distribution Losses,Electricity,1135.38,GWh
19,Australia,December 2025,Final Consumption (Calculated),Electricity,22144.5943,GWh

In [123]:
df = df.drop(df.index[0:7], axis = 0)
df.reset_index(drop = True)

,The Monthly electricity data explorer and the main highlights are available here: https://www.iea.org/reports/monthly-electricity-statistics-overview,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5
0,Country,Time,Balance,Product,Value,Unit
1,Australia,December 2025,Net Electricity Production,Electricity,23360.4375,GWh
2,Australia,December 2025,Net Electricity Production,Hydro,932.8479,GWh
3,Australia,December 2025,Net Electricity Production,Total Combustible Fuels,12210.7489,GWh
4,Australia,December 2025,Net Electricity Production,"Coal, Peat and Manufactured Gases",8782.6749,GWh
...,...,...,...,...,...,...
158174,IEA Total,January 2010,Total Exports,Electricity,32372.583,GWh
158175,IEA Total,January 2010,Used for pumped storage,Electricity,6869.253,GWh
158176,IEA Total,January 2010,Distribution Losses,Electricity,62000.733,GWh
158177,IEA Total,January 2010,Final Consumption (Calculated),Electricity,877213.615,GWh
158178,IEA Total,January 2010,Net Electricity Production,Wind,21659.612,GWh

In [124]:
df.columns

Index(['The Monthly electricity data explorer and the main highlights are available here: https://www.iea.org/reports/monthly-electricity-statistics-overview',
       'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4', 'Unnamed: 5'],
      dtype='object')

In [125]:
df.columns = df.iloc[0]
df.drop(7, inplace=True)

In [126]:
df.reset_index(drop = True)
df.columns.name = None

In [132]:
df.columns

Index(['Country', 'Time', 'Balance', 'Product', 'Value', 'Unit'], dtype='object')

In [136]:
nulos = df.isnull()
nulos.sum()

Country    0
Time       0
Balance    0
Product    0
Value      0
Unit       0
dtype: int64

In [140]:
colombia = df[df['Country'] == 'Colombia']
colombia.reset_index(drop = True)

,Country,Time,Balance,Product,Value,Unit
0,Colombia,December 2025,Net Electricity Production,Electricity,7794.9781,GWh
1,Colombia,December 2025,Net Electricity Production,Hydro,5530.6545,GWh
2,Colombia,December 2025,Net Electricity Production,Total Combustible Fuels,1764.6682,GWh
3,Colombia,December 2025,Net Electricity Production,"Coal, Peat and Manufactured Gases",483.3555,GWh
4,Colombia,December 2025,Net Electricity Production,Oil and Petroleum Products,287.5943,GWh
...,...,...,...,...,...,...
2341,Colombia,January 2014,Total Imports,Electricity,0.021,GWh
2342,Colombia,January 2014,Total Exports,Electricity,146.888,GWh
2343,Colombia,January 2014,Distribution Losses,Electricity,536.164,GWh
2344,Colombia,January 2014,Final Consumption (Calculated),Electricity,5019.684,GWh
2345,Colombia,January 2014,Net Electricity Production,Wind,5.648,GWh

In [ ]:
productos = colombia[colombia['Product']].sum()

KeyError: "None of [Index(['Electricity', 'Hydro', 'Total Combustible Fuels',\n       'Coal, Peat and Manufactured Gases', 'Oil and Petroleum Products',\n       'Natural Gas', 'Combustible Renewables', 'Solar',\n       'Total Renewables (Hydro, Geo, Solar, Wind, Other)', 'Electricity',\n       ...\n       'Oil and Petroleum Products', 'Natural Gas', 'Combustible Renewables',\n       'Solar', 'Total Renewables (Hydro, Geo, Solar, Wind, Other)',\n       'Electricity', 'Electricity', 'Electricity', 'Electricity', 'Wind'],\n      dtype='object', length=2346)] are in the [index]"